services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: osmelcrespo
      SINGLE_USER_CREDENTIALS_PASSWORD: ey6vmkMVdGJBcDNC!!
    restart: unless-stopped