version: '3.7'
services:
  pg-admin:
    image: dpage/pgadmin4:latest
    ports:
      - '8086:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=osmel.e.crespo@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=9&W~Pc]dcV
    volumes:
      - db:/var/lib/pgadmin
    restart: unless-stopped
volumes:
  db: