apiVersion: v1
kind: PersistentVolume
metadata:
  name: splunk-data
  #namespace: postgres-system
spec:  
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.1.220
    path: /mnt/p-main/kube/splunk