apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-data-claim
  #namespace: postgres-system
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi