apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch.ocrespo
  namespace: default
spec:
  dnsNames:
    - elasticsearch.ocrespo.com
    - kibana.ocrespo.com
  secretName: elasticsearch.ocrespo
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer