version: '3.7'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - '8123:8123'
    environment:
      - TZ=America/New_York
    volumes:
      - db:/config
    restart: unless-stopped
volumes:
  db: