apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data
  namespace: postgres-system
spec:  
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.1.31
    path: "/srv/data/postgres"