apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-claim
  namespace: postgres-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi