apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  #namespace: postgres-system
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: u#g7SCBQ4^x9L_dr
  PGDATA: /var/lib/postgresql/data/pgdata