version: "3.2"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "3010:1433"
    environment:
      SA_PASSWORD: "change_this_password"
      ACCEPT_EULA: "Y"      
    volumes: 
        - D:\DATABASES\DOCKER-DB\BACKUP:/var/opt/mssql/backups
        - D:\DATABASES\DOCKER-DB\SQLSERVER:/var/opt/sqlserver
        - D:\DATABASES\DOCKER-DB\MSSQL:/var/opt/mssql